yazlabyeni/Controllers/TrainerController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using yazlabyeni.Models;

namespace yazlabyeni.Controllers
{
    public class TrainerController : Controller
    {
        TrainerManager trainerManager = new TrainerManager();
        UserManager userManager = new UserManager();
        UserTrainerManager UserTrainerManager = new UserTrainerManager(new EfUserTrainerRepository());
        DietManager DietManager = new DietManager();
        DietListsManager DietListsManager = new DietListsManager();
        ExercisesListsManager ExercisesListsManager = new ExercisesListsManager();
        TrainerDietManager trainerDietManager = new TrainerDietManager(new EfTrainerDietRepository());
        TrainerExerciseManager TrainerExerciseManager = new TrainerExerciseManager(new EfTrainerExerciseRepository());
       
        public IActionResult Index()
        {
            var p = HttpContext.Session.GetString("Mail");
            Trainer trainer = trainerManager.GetTrainerByEmail(p);

            return View(trainer);
        }

        [HttpPost]
        public IActionResult TrainerProfileInfoUpdate(Trainer trainer)
        {
            trainerManager.Update(trainer);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult AddImage(AddTrainerPhoto p)
        {
            var A = HttpContext.Session.GetString("Mail");
            Trainer u = trainerManager.GetTrainerByEmail(A);
            if (p.TrainerPhoto != null)
            {
                var extensions = Path.GetExtension(p.TrainerPhoto.FileName);
                var newImageName = Guid.NewGuid() + extensions;
                var location = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images/", newImageName);
                var stream = new FileStream(location, FileMode.Create);
                p.TrainerPhoto.CopyTo(stream);
                u.TrainerPhoto = newImageName;

            }

            trainerManager.Update(u);
            return RedirectToAction("Index");

        }
      

        public IActionResult TrainerDefaultDiets()
        {
            Trainer trainer = trainerManager.GetTrainerByEmail(HttpContext.Session.GetString("Mail"));
            var includeDiets = trainerDietManager.GetDietByTrainer(trainer.TrainerId);
            var allDiets = DietListsManager.GetAllLists();

            var dietViewModels = new List<DietViewModel>();

            foreach (var diet in allDiets)
            {
                var dietViewModel = new DietViewModel
                {
                    DietView = diet,
                    IsInclude =includeDiets.Any(d=>d.DietList.DietListId == diet.DietListId && d.Status == true)
                };

                dietViewModels.Add(dietViewModel);
            }

            Console.WriteLine(dietViewModels.Count);

            return View(dietViewModels);
        }

        public IActionResult TrainerDefaultExercises()
        {
            Trainer trainer = trainerManager.GetTrainerByEmail(HttpContext.Session.GetString("Mail"));
            var includeExercises = TrainerExerciseManager.GetTrainerExerciseById(trainer.TrainerId);
            var allExercise = ExercisesListsManager.GetAllExercises();

            var exerciseViewModels = new List<ExerciseViewModel>();

            foreach (var exercise in allExercise)
            {
                var exerciseViewModel = new ExerciseViewModel
                {
                    ExerciseList = exercise,
                    IsIncluded = includeExercises.Any(d=>d.ExerciseList.ExerciseListId == exercise.ExerciseListId && d.Status == true)
                };

                exerciseViewModels.Add(exerciseViewModel);
            }

            return View(exerciseViewModels);
        }
        public IActionResult ExerciseStatusTrue(int Id)
        {
            Trainer trainer = trainerManager.GetTrainerByEmail(HttpContext.Session.GetString("Mail"));
            TrainerExerciseManager.InsertExercise(trainer.TrainerId, Id);
            return RedirectToAction("TrainerDefaultExercises");
        }

        public IActionResult ExerciseStatusFalse(int Id)
        {
            Trainer trainer = trainerManager.GetTrainerByEmail(HttpContext.Session.GetString("Mail"));
            TrainerExerciseManager.DeleteExercise(trainer.TrainerId, Id);
            return RedirectToAction("TrainerDefaultExercises");
        }
        public IActionResult DietStatusTrue(int Id)
        {
            Trainer trainer = trainerManager.GetTrainerByEmail(HttpContext.Session.GetString("Mail"));
            trainerDietManager.InsertDiet(trainer.TrainerId, Id);
            return RedirectToAction("TrainerDefaultDiets");
        }

        public IActionResult DietStatusFalse(int Id)
        {
            Trainer trainer = trainerManager.GetTrainerByEmail(HttpContext.Session.GetString("Mail"));
            trainerDietManager.DeleteDiet(trainer.TrainerId, Id);
            return RedirectToAction("TrainerDefaultDiets");
        }

        public IActionResult TrainerUserApplication()
        {
            Trainer trainer = trainerManager.GetTrainerByEmail(HttpContext.Session.GetString("Mail"));
            var appliedUserList = UserTrainerManager.GetUserTrainersByTrainerId(trainer.TrainerId);

            return View(appliedUserList);
        }

        public IActionResult UserApplicationStatusTrue(int Id)
        {
            UserTrainerManager.StatusChangeTrue(Id);

            return RedirectToAction("TrainerUserApplication");
        }
        public IActionResult UserApplicationStatusFalse(int Id)
        {
            UserTrainerManager.StatusChangeFalse(Id);

            return RedirectToAction("TrainerUserApplication");
        }

        [Authorize(Roles =("User,Admin,Trainer"))]
        [HttpPost]
        public IActionResult UserApplication(int id)
        {
            string  getUser = HttpContext.Session.GetString("Mail");
            User user = userManager.GetUserByEmail(getUser);

            UserTrainer userTrainer = new UserTrainer
            {
                TrainerID = id,
                UserID = user.UserId

            };

            UserTrainerManager.InsertUserTrainer(userTrainer);

            return RedirectToAction("TrainerPage", new { trainerId = id });
        }

        public IActionResult TrainerPage(int trainerId)
        {
            return View(trainerId);
        }
    }
}

yazlabyeni/Views/Trainer/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TrainerLayout.cshtml";
}


@model EntityLayer.Concrete.Trainer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <title>Profil Kartı</title>
    <style>
        body {
            background-color: #f8f9fa;
            padding: 20px;
        }

        .profile-card {
            max-width: 400px;
            margin: 0 auto;
            background-color: #ffffff;
            border: 1px solid #dee2e6;
            border-radius: 8px;
            padding: 20px;
            margin-top: 1px;
        }

        .profile-image {
            width: 100%;
            border-radius: 50%;
        }

        .edit-button {
            margin-top: 10px;
        }
    </style>
</head>
<body>

    <div class="profile-card">
        <img src="/Images/@Model.TrainerPhoto" alt="Profil Resmi" class="profile-image">
        <h2>Kullanıcı Adı : @Model.Name @Model.Surname</h2>
        <p>Email: @Model.Mail</p>
        <p>Telefon: @Model.PhoneNumber</p>
        <p>Açıklama: @Model.Description</p>
        <p>Uzmanlık: @Model.Expertise</p>

        <div class="d-flex justify-content-between">
            <button class="btn btn-primary btn-sm edit-button" data-toggle="modal" data-target="#editModal">Profili Düzenle</button>

            <form class="form-inline" action="@Url.Action("AddImage", "Trainer")" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    @Html.Label("Profil Resmi")
                    <input type="file" class="form-control-file" name="TrainerPhoto" />
                </div>
                <button type="submit" class="btn btn-primary btn-sm edit-button ml-2">Resmi Güncelle</button>
            </form>
        </div>

    </div>

    <!-- Profil Düzenleme Modal -->
    <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editModalLabel">Profil Düzenleme</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- Düzenleme Formu -->
                    @using (Html.BeginForm("TrainerProfileInfoUpdate", "Trainer", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(x => x.TrainerId)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Surname, new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.Surname, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Mail, new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.Mail, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.Description, new { @class = "form-control"})
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Expertise, new { @class = "control-label" })
                            @Html.DropDownListFor(model => model.Expertise, new SelectList(new[] { "Kas Kazanma", "Yağ Yakma", "Fit Olma", "Ödem Atma", "Boy Uzatma", "Genel Spor" }), new { @class = "form-control" })
                        </div>
                        <button type="submit" class="btn btn-primary">Kaydet</button>
                    }

                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap ve jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

</body>
</html>

yazlabyeni/Views/Trainer/TrainerDefaultDiets.cshtml
@{
    ViewData["Title"] = "TrainerDefaultDiets";
    Layout = "~/Views/Shared/_TrainerLayout.cshtml";
}



@model IEnumerable<DietViewModel>;

<div class="container mt-5">
    <div class="row">
        <div class="col-12">
            <table class="table table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Durum</th>
                        <th scope="col">Kahvaltı</th>
                        <th scope="col">Öğle Yemeği</th>
                        <th scope="col">Akşam Yemeği</th>
                        <th scope="col">Günlük Kalori</th>
                        <th scope="col">İşlem</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var x in Model)
                    {
                        <tr>
                            @if (x.IsInclude == true)
                            {
                                <td>Ekli</td>
                            }
                            @if (x.IsInclude == false)
                            {
                                <td>Ekli Değil</td>
                            }

                            <td>@x.DietView.Breakfast</td>
                            <td>@x.DietView.Lunch</td>
                            <td>@x.DietView.Dinner</td>
                            <td>@x.DietView.DailyCalories</td>
                            <td>
                                <div style="display: flex; gap: 8px;">
                                    <form action="/Trainer/DietStatusTrue" method="get">
                                        <input type="hidden" name="Id" value="@x.DietView.DietListId" />
                                        <button type="submit" class="btn btn-outline-success">Ekle</button>
                                    </form>

                                    <form action="/Trainer/DietStatusFalse" method="get">
                                        <input type="hidden" name="Id" value="@x.DietView.DietListId" />
                                        <button type="submit" class="btn btn-outline-danger">Çıkar</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

yazlabyeni/Views/Trainer/TrainerDefaultExercises.cshtml
@{
    ViewData["Title"] = "TrainerDefaultExercises";
    Layout = "~/Views/Shared/_TrainerLayout.cshtml";
}



@model IEnumerable<ExerciseViewModel>;

<div class="container mt-5">
    <div class="row">
        <div class="col-12">
            <table class="table table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Durum</th>
                        <th scope="col">İsim</th>
                        <th scope="col">Hedef</th>
                        <th scope="col">Açıklama</th>
                        <th scope="col">Set</th>
                        <th scope="col">İşlem</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var x in Model)
                    {
                        <tr>
                            @if (x.IsIncluded == true)
                            {
                                <td>Ekli</td>
                            }
                            @if (x.IsIncluded == false)
                            {
                                <td>Ekli Değil</td>
                            }

                            <td>@x.ExerciseList.Name</td>
                            <td>@x.ExerciseList.Target</td>
                            <td>@x.ExerciseList.Description.Substring(0, x.ExerciseList.Description.Substring(0, 100).LastIndexOf(" ")) ... </td>
                            <td>@x.ExerciseList.Set</td>
                            <td>
                                <div style="display: flex; gap: 8px;">
                                    <form action="/Trainer/ExerciseStatusTrue" method="get">
                                        <input type="hidden" name="Id" value="@x.ExerciseList.ExerciseListId" />
                                        <button type="submit" class="btn btn-outline-success">Ekle</button>
                                    </form>

                                    <form action="/Trainer/ExerciseStatusFalse" method="get">
                                        <input type="hidden" name="Id" value="@x.ExerciseList.ExerciseListId" />
                                        <button type="submit" class="btn btn-outline-danger">Çıkar</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

yazlabyeni/Views/Trainer/TrainerPage.cshtml
@{
    ViewData["Title"] = "TrainerPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model int

@await Component.InvokeAsync("TrainerAbout",Model)

</br>

<div class="text-center">

    <h2>Egzersiz Listesi</h2>
</div>

</br>

@await Component.InvokeAsync("TrainerExerciseList")

</br>

<div class="text-center">

    <h2>Diyet Listesi</h2>
</div>

</br>

@await Component.InvokeAsync("TrainerDietList")

</br>


</br>
@await Html.PartialAsync("_Footer","Shared")

yazlabyeni/Views/Trainer/TrainerUserApplication.cshtml
@{
    ViewData["Title"] = "TrainerUserApplication";
    Layout = "~/Views/Shared/_TrainerLayout.cshtml";
}




@model IEnumerable<EntityLayer.Concrete.UserTrainer>;

<div class="container mt-5">
    <div class="row">
        <div class="col-12">
            <table class="table table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Durum</th>
                        <th scope="col">Resim</th>
                        <th scope="col">İsim</th>
                        <th scope="col">Soy İsim</th>
                        <th scope="col">Doğum Tarihi</th>
                        <th scope="col">E-Mail</th>
                        <th scope="col">Cinsiyet</th>
                        <th scope="col">İşlem</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var x in Model)
                    {
                        <tr>
                            @if (x.Status == true)
                            {
                                <td>Ekli</td>
                            }
                            @if (x.Status == false)
                            {
                                <td>Ekli Değil</td>
                            }

                            <td >
                                <div class="col-5 text-center">
                                    <img src="/Images/@x.User.PhotoUrl" alt="" class="img-circle img-fluid" style="max-width: 50px; max-height: 50px;">
                                </div>
                            </td>
                            <td>@x.User.Name</td>
                            <td>@x.User.Surname</td>
                            <td>@x.User.BirthDate</td>
                            <td>@x.User.Mail</td>
                            <td>@x.User.Sex</td>
                            <td>
                                <div style="display: flex; gap: 8px;">
                                    <form action="/Trainer/UserApplicationStatusTrue" method="get">
                                        <input type="hidden" name="Id" value="@x.UserTrainerID" />
                                        <button type="submit" class="btn btn-outline-success">Ekle</button>
                                    </form>

                                    <form action="/Trainer/UserApplicationStatusFalse" method="get">
                                        <input type="hidden" name="Id" value="@x.UserTrainerID" />
                                        <button type="submit" class="btn btn-outline-danger">Çıkar</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>